<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="44328" started-at="2015-06-15T17:43:47Z" finished-at="2015-06-15T17:44:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="44328" started-at="2015-06-15T17:43:47Z" finished-at="2015-06-15T17:44:32Z">
      <class name="com.LoginAndRegisterModules.NikeSoccer_SignIn">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.LoginAndRegisterModules.NikeSoccer_SignIn@126099c]" name="setup" is-config="true" duration-ms="17505" started-at="2015-06-15T23:13:47Z" finished-at="2015-06-15T23:14:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="signIn()[pri:0, instance:com.LoginAndRegisterModules.NikeSoccer_SignIn@126099c]" name="signIn" duration-ms="25571" started-at="2015-06-15T23:14:05Z" finished-at="2015-06-15T23:14:30Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.LoginAndRegisterModules.NikeSoccer_SignIn.signIn(NikeSoccer_SignIn.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.LoginAndRegisterModules.NikeSoccer_SignIn@126099c]" name="tearDown" is-config="true" duration-ms="1236" started-at="2015-06-15T23:14:30Z" finished-at="2015-06-15T23:14:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.LoginAndRegisterModules.NikeSoccer_SignIn -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
